apiVersion: v1
kind: Service
metadata:
  name: php-serv
  labels:
    app: php
  annotations:
    metallb.universe.tf/allow-shared-ip: shared
spec:
  selector:
    app: php
  type: LoadBalancer
  loadBalancerIP: 192.168.99.121
  ports:
    - protocol: TCP
      name: http
      port: 5000
      targetPort: 5000
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: php-deployment
  labels:
    app: php
spec:
  replicas: 1
  strategy:
    type: Recreate
  selector:
    matchLabels:
      app: php
  template:
    metadata:
      name: php-pod
      labels:
        app: php
    spec:
      containers:
      - name: php
        image: php_image
        imagePullPolicy: Never
        ports:
          - containerPort: 5000
